import turtle

class number3:
    def __init__(self):
        self.position = (270, 0)

    def draw(self):
        turtle.color("#FFFF00")
        turtle.penup()
        turtle.goto(self.position)
        turtle.pendown()
        turtle.setheading(180)
        turtle.forward(27)
        turtle.setheading(0)
        turtle.forward(13)
        turtle.penup()
        turtle.goto(self.position)
        turtle.pendown()
        turtle.setheading(60)
        turtle.forward(27)
        turtle.setheading(120)
        turtle.forward(27)
        turtle.setheading(180)
        turtle.forward(27)
        turtle.setheading(240)
        turtle.forward(18)
        turtle.penup()
        turtle.goto(self.position)
        turtle.pendown()
        turtle.setheading(300)
        turtle.forward(27)
        turtle.setheading(240)
        turtle.forward(27)
        turtle.setheading(180)
        turtle.forward(27)
        turtle.setheading(120)
        turtle.forward(18)
        #turtle.mainloop()
if __name__ == '__main__':
    three=number3()
    three.draw()
    turtle.mainloop()